# Generated by Django 4.0 on 2023-10-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
