# Generated by Django 4.0 on 2023-10-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_user_profile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
    ]
